### ISSUE TITLE
[기능 요청]

### ISSUE THREAD

**Issue by hyejun0608** [DSM-SUBMIT/rms_backend_node#44]
**이 요청 사항이 사용 중 불편함과 관련된 내용인가요? 만약 그렇다면 어떤 불편함이 있었는지 적어 주세요.**
*간결하고 확실하게!*
팀 프로젝트인지 개인 프로젝트인지 구분을 못해요..

**어떤 식으로 개선되었으면 좋겠는지 적어 주세요.**
팀 프로젝트인지 개인 프로젝트인지 구분할 수 있는 response를 넘겨줬으면 좋겠어요!!

**추가적으로 다른 솔루션이 있다면 적어 주세요.**
boolean 값으로 넘겨주세요

**Comment by pjp0704** [comment]
1. 계획서 / 보고서 상세 보기에만 해당 필드가 필요한가요?
2. 프로젝트 목록에도 해당 필드가 필요한가요?
3. 아니면 계획서 / 보고서 상세 보기에 해당 필드를 넘기고, 동시에 프로젝트 목록을 개인 / 팀 구별할 수 있게 만드는 게 더 편한가요?

**Comment by hyejun0608** [comment]
어드민 보고서 / 계획서에는 이미 구분할 수 있는 필드가 있다고 하네요..? 친구들이 말을 안해줘서 몰랐어요 그럼 목록은 필드로 유지하고 상세보기에만 추가해주시면 매우 감사하겠습니다

**Comment by pjp0704** [comment]
team_name 필드가 존재하긴 하는데, 해당 필드는 말 그대로 팀명이라 개인인지 팀인지를 구별하는 용도로는 부적합할 거라서, 목록에도 따로 구분 필드를 만드는 것이 좋을 것 같다는 생각이 드네요.

그리고 개인과 팀의 구분 기준이 어떻게 될까요? 개인 프로젝트가 아니면 전부 팀 프로젝트로 취급하는 건가요?

**Comment by pjp0704** [comment]
그럼 쿼리 구별은 안 하고 필드만 추가하는 걸로 작업하겠습니당
