### ISSUE TITLE
[버그]

### ISSUE THREAD

**Issue by hyejun0608** [DSM-SUBMIT/rms_backend_node#49]
**버그 설명**
[GET] /projects/{projectId}/report 보고서 상세보기 api에서 500오류가 뜹니다.  
그런데 500의 기준을 모르겠어요 6번 보고서는 200이 뜨는데 19번 보고서는 500이 떠요.  
다른 점이라면 6번은 이미 승인요청이 수락된 상태이고, 19번은 승인요청중인 보고서입니다...

**재현 과정**
api를 호출하면 됩니다. (500이 떴던 보고서 번호는 19번이고요)

**원래 예상했던 동작**
완전 값이 잘 받아지는 것이요

**스크린샷**
![image](https://user-images.githubusercontent.com/63457172/136351476-7339e0ba-084d-40fe-be7e-60151bf0c128.png)

**사용 환경**
로컬 브라우저에서 api 연동중이였습니담

**Comment by pjp0704** [comment]
프로젝트 생성 시 계획서와 보고서가 동시에 생성되는 것으로 유저 백엔드가 수정되면서, 일반적인 상황에서는 해당 오류가 발생할 일이 사라졌습니다. 따라서 당장은 수정될 예정이 없을 것 같습니다..
다음 패치 때 같이 포함될 수도 있겠지만 우선 500만 안 나오도록 조치될 가능성이 높아 보입니다
